group 'com.amazon.flutter_amazonpaymentservices'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://android-sdk.payfort.com" }

    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://android-sdk.payfort.com" }

    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.amazon.flutter_amazonpaymentservices'
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion 21
    }
    dependencies {

        implementation('com.amazon:fortpayment:+:release@aar') {
            transitive = true
        }
    }
}
